#!/bin/bash
# remove restriction to French networks
/usr/sbin/iptables -R INPUT 9 -p tcp -m tcp --dport 80 -j ACCEPT
/usr/sbin/iptables -R INPUT 10 -p tcp -m tcp --dport 443 -j ACCEPT
/usr/bin/certbot -q renew
/bin/systemctl restart netfilter-persistent
/bin/systemctl reload nginx
